# Generated by Django 4.2 on 2026-06-05 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PVSystem",
            fields=[
                (
                    "system_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "capacity_kwc",
                    models.FloatField(help_text="Puissance crête installée en kWc"),
                ),
                (
                    "commissioning_date",
                    models.DateField(help_text="Date de mise en service"),
                ),
                (
                    "inclination",
                    models.FloatField(
                        default=25, help_text="Inclinaison des panneaux en degrés"
                    ),
                ),
                ("orientation", models.CharField(default="South", max_length=30)),
                (
                    "nb_strings",
                    models.IntegerField(default=0, help_text="Nombre de strings"),
                ),
            ],
            options={
                "ordering": ["system_id"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "module_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                (
                    "technology",
                    models.CharField(help_text="Ex: Mono-Si, Mono PERC", max_length=50),
                ),
                ("power_wc", models.FloatField(help_text="Puissance unitaire en Wc")),
                (
                    "voc_v",
                    models.FloatField(default=0, help_text="Tension en circuit ouvert"),
                ),
                (
                    "isc_a",
                    models.FloatField(default=0, help_text="Courant de court-circuit"),
                ),
                ("nb_modules", models.IntegerField(default=0)),
                (
                    "system",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module",
                        to="api.pvsystem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inverter",
            fields=[
                (
                    "inverter_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("power_kw_ac", models.FloatField(help_text="Puissance AC en kW")),
                ("nb_mppt", models.IntegerField(help_text="Nombre d'entrées MPPT")),
                ("serial_number", models.CharField(max_length=100)),
                (
                    "system",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inverter",
                        to="api.pvsystem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DCProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("dc_power_kw", models.FloatField(help_text="Puissance DC en kW")),
                ("dc_voltage_v", models.FloatField(help_text="Tension DC en V")),
                ("dc_current_a", models.FloatField(help_text="Courant DC en A")),
                (
                    "irradiance_wm2",
                    models.FloatField(help_text="Irradiance solaire en W/m²"),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dc_production",
                        to="api.pvsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ACProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("ac_power_kw", models.FloatField(help_text="Puissance AC en kW")),
                ("ac_energy_kwh", models.FloatField(help_text="Énergie AC en kWh")),
                ("ac_voltage_v", models.FloatField(help_text="Tension AC en V")),
                (
                    "power_factor",
                    models.FloatField(help_text="Facteur de puissance (0–1)"),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ac_production",
                        to="api.pvsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="dcproduction",
            index=models.Index(
                fields=["system", "timestamp"], name="api_dcprodu_system__ebe361_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dcproduction",
            unique_together={("timestamp", "system")},
        ),
        migrations.AddIndex(
            model_name="acproduction",
            index=models.Index(
                fields=["system", "timestamp"], name="api_acprodu_system__f9c956_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="acproduction",
            unique_together={("timestamp", "system")},
        ),
    ]
