# Generated by Django 4.2 on 2026-06-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_nb_modules_module_nb_per_string_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inverter",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inverter",
                to="api.pvsystem",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module",
                to="api.pvsystem",
            ),
        ),
    ]
